name: spotify-box
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'  # Runs at 00:00 UTC every day
  push:
    branches: main
jobs:
  updateTopTracks:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update
        run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
